version: "3"
services:
    app_service:
        build: ./app/
        image: ltneric/ltn2017:latest
        networks:
          - frontend
        #volumes:
        #  - $PWD/app:/app
        deploy:
          replicas: 1
          update_config:
            parallelism: 1
          restart_policy:
            condition: on-failure
        environment:
          - DEBUG=False
          #- MAIL_PASSWORD="skjqw0pvn@#Rar23#^(&^%"
        env_file:
          - secrets.env
networks:
    frontend:
